#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : configparser
Version  : 4.0.1
Release  : 48
URL      : https://files.pythonhosted.org/packages/c4/75/0ed2711aab826e48baff301f7a3d045e23a562ccfe1ff992be935f02ac9f/configparser-4.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c4/75/0ed2711aab826e48baff301f7a3d045e23a562ccfe1ff992be935f02ac9f/configparser-4.0.1.tar.gz
Summary  : Updated configparser from Python 3.7 for Python 2.6+.
Group    : Development/Tools
License  : MIT
Requires: configparser-license = %{version}-%{release}
Requires: configparser-python = %{version}-%{release}
Requires: configparser-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : setuptools
BuildRequires : setuptools-legacypython
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv

%description
.. image:: https://img.shields.io/pypi/v/configparser.svg
:target: https://pypi.org/project/configparser

%package license
Summary: license components for the configparser package.
Group: Default

%description license
license components for the configparser package.


%package python
Summary: python components for the configparser package.
Group: Default
Requires: configparser-python3 = %{version}-%{release}

%description python
python components for the configparser package.


%package python3
Summary: python3 components for the configparser package.
Group: Default
Requires: python3-core

%description python3
python3 components for the configparser package.


%prep
%setup -q -n configparser-4.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568150662
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/configparser
cp LICENSE %{buildroot}/usr/share/package-licenses/configparser/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.7/site-packages/backports/__init__.py
rm -f %{buildroot}/usr/lib/python3.7/site-packages/backports/__pycache__/__init__.cpython-37.pyc

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/configparser/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
